# ---------- Cursor ----------
cursor            #ffb4a4
cursor_text_color #561f13
# ---------- Cursor ----------

# ---------- Base ----------
foreground           #f1dfdb
background           #1a110f
selection_foreground #442a24
selection_background #e7bdb4
url_color            #e7bdb4
# ---------- Base ----------

# ---------- ANSI Colors ----------
# Black
color0 #1a110f
color8 #3d3230

# Red
color1 #000000
color9 #343a3a

# Green
color2  #e7bdb4
color10 #ffdad3

# Yellow
color3  #dbc58c
color11 #f8e0a6

# Blue
color4  #733426
color12 #ffb4a4

# Magenta
color5  #5d3f39
color13 #e7bdb4

# Cyan
color6  #544519
color14 #dbc58c

# White
color7  #d8c2bd
color15 #f1dfdb
# ---------- ANSI Colors ----------

# ---------- Marks ----------
mark1_foreground #3a0a03
mark1_background #ffdad3
mark2_foreground #2c1510
mark2_background #ffdad3
mark3_foreground #241a00
mark3_background #f8e0a6
# ---------- Marks ----------

# ---------- Tabs ----------
active_tab_foreground   #561f13
active_tab_background   #ffb4a4
inactive_tab_foreground #ffdad3
inactive_tab_background #733426
# ---------- Tabs ----------

# ---------- Borders ----------
active_border_color   #ffb4a4
inactive_border_color #561f13
# ---------- Borders ----------
